plugins { id 'com.android.application' }
android {
    namespace 'fr.tibo.iamanager'
    compileSdk 35
    defaultConfig {
        applicationId 'fr.tibo.iamanager.mobile'
        minSdk 26
        targetSdk 35
        versionCode 57
        versionName '0.1-v57'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    lint { abortOnError true }
}
